!#ident expgpn.F from deck xeg                                                /*xeg         1*/
      subroutine expgpn                                                         !/*xeg         2*/
!        remove unneeded data from table type u                                 !/*xeg         3*/
!                                                                               !/*xeg         4*/
      use global_data                                                           !/*xeg         5*/
!                                                                               !/*xeg         6*/
      implicit real(kindr) (a-h,o-z)                                            !/*xeg         7*/
      implicit integer(kindi) (i-n)                                             !/*xeg         8*/
!                                                                               !/*xeg         9*/
!                                                                               !/*xeg        10*/
      return                                                                    !/*xeg        11*/
      end                                                                       !/*xeg        12*/
