!#ident srcdx.F from deck sx                                                    !/*sx          1*/
      subroutine srcdx                                                          !/*sx          2*/
!        dummy subroutine.                                                      !/*sx          3*/
      use global_data                                                           !/*sxx         1*/
!                                                                               !/*sxx         2*/
      implicit real(kindr) (a-h,o-z)                                            !/*sxx         3*/
      implicit integer(kindi) (i-n)                                             !/*sxx         4*/
!                                                                               !/*sxx         5*/
!                                                                               !/*sx          5*/
      return                                                                    !/*sx          6*/
      end                                                                       !/*sx          7*/
