!     $Id: stars.h,v 1.4 2002/03/27 18:14:18 gwm Exp $                        !/*st          1*/
!----------------------------------------------------------------------*        !/*st          2*/
!     include file: stars copy              created 26/11/86 by pa     *        !/*st          3*/
!     changes: none                                                    *        !/*st          4*/
!     included in the following subroutines or functions: not updated  *        !/*st          5*/
!                                                                      *        !/*st          6*/
!     description of the common block(s) and variable(s)               *        !/*st          7*/
!                                                                      *        !/*st          8*/
!                                                                      *        !/*st          9*/
!     /stars/ contains information of the stars generated              *        !/*st         10*/
!        ntstar = total number of stars generated                      *        !/*st         11*/
!        wstars = total weight of the stars generated                  *        !/*st         12*/
!        westar = weight of the stars generated by                     *        !/*st         13*/
!                 different particle types                             *        !/*st         14*/
!        westop = total weight of the particles stopped                *        !/*st         15*/
!        wstop  = weight of particles of different types stopped       *        !/*st         16*/
!        weisec = total weight of the secondaries created              *        !/*st         17*/
!        weipri = total weight of the primaries handled                *        !/*st         18*/
!        edi    = deposited energy                                     *        !/*st         19*/
!                 edi(1) = by ionisation                               *        !/*st         20*/
!                 edi(2) = by pi-zeros                                 *        !/*st         21*/
!                 edi(3) = by nuclear excitation                       *        !/*st         22*/
!                 edi(4) = by stopped particles                        *        !/*st         23*/
!                 edi(5) = energy leaving the system                   *        !/*st         24*/
!        wdec   = weight of the particles decayed                      *        !/*st         25*/
!        wdau   = weight of the decay-products                         *        !/*st         26*/
!        wtdec  = total weight of the particles decayed                *        !/*st         27*/
!        wtdau  = total weight of the decay products                   *        !/*st         28*/
!        numdec = total number of decays                               *        !/*st         29*/
!----------------------------------------------------------------------*        !/*st         30*/
      common /stars/ wstars, westar(30), westop, wstop(30), weisec(30),         !/*st         31*/
     & weipri, edi(5), wdec(30), wdau(30), wtdec, wtdau, numdec, ntstar         !/*st         32*/
