C SCHMID-WILDERMUTH POTENTIAL 

C CHANNEL RANGE MATRIX ELEMENT CAL.

      SUBROUTINE SWFRC(ZH,DL,ZA1,ZA2) 
      INCLUDE 'LI_INC.f'
      ZH  =(0.D0,0.D0)
      ZT  =(0.D0,0.D0)
      ZSW =(0.D0,0.D0)
      ZCLB=(0.D0,0.D0)
      ZPF =(0.D0,0.D0)
      CALL KINE(ZT,DL,ZA1,ZA2)
      CALL CENT(ZSW,DL,ZA1,ZA2)
      CALL COULOMB(ZCLB,DL,ZA1,ZA2)
      CALL ZSEUDO(ZPF,DL,ZA1,ZA2)
      ZH=ZT+ZSW+ZCLB+ZPF
      RETURN
      END
      
C ASYMPTOTIC MATRIX ELEMENT CAL.

      SUBROUTINE SWFRC0(ZH0,DL,ZA1,ZA2) 
      INCLUDE 'LI_INC.f'
      ZH0=(0.D0,0.D0)
      ZT=(0.D0,0.D0)
      ZCLB0=(0.D0,0.D0)
      CALL KINE(ZT,DL,ZA1,ZA2)
      CALL COULOMB0(ZCLB0,DL,ZA1,ZA2)
      ZH0=ZT+ZCLB0
      RETURN
      END

C BUCK POTENTIAL 

C CHANNEL RANGE MATRIX ELEMENT CAL.

      SUBROUTINE BUCK(ZH,DL,ZA1,ZA2) 
      INCLUDE 'LI_INC.f'
      ZH  =(0.D0,0.D0)
      ZT  =(0.D0,0.D0)
      ZBK =(0.D0,0.D0)
      ZCLB=(0.D0,0.D0)
      CALL KINE(ZT,DL,ZA1,ZA2)
      CALL BCENT(ZBK,DL,ZA1,ZA2)
      CALL BCOULOMB(ZCLB,DL,ZA1,ZA2)
      ZH=ZT+ZBK+ZCLB
      RETURN
      END
      
C ASYMPTOTIC MATRIX ELEMENT CAL.

      SUBROUTINE BUCK0(ZH0,DL,ZA1,ZA2) 
      INCLUDE 'LI_INC.f'
      ZH0=(0.D0,0.D0)
      ZT=(0.D0,0.D0)
      ZCLB0=(0.D0,0.D0)
      CALL KINE(ZT,DL,ZA1,ZA2)
      CALL COULOMB0(ZCLB0,DL,ZA1,ZA2)
      ZH0=ZT+ZCLB0
      RETURN
      END
