!     $Id: e0bd.F,v 1.4 2002/03/27 18:15:01 gwm Exp $                         !/*e0          1*/
      block data e0bd                                                           !/*e0          2*/
#include <lcs/double.h>                                                         /*!e0          3*/
#include <lcs/orcm.h>                                                           /*!e0          4*/
      data qfactr /dp10/, ismal /2/, iversn /1/, ro /1.2d0/, kemax /6/          !/*e0          5*/
      end                                                                       !/*e0          6*/
