!     $Id: pqbd.F,v 1.4 2002/03/27 18:15:16 gwm Exp $                         !/*pq          1*/
      block data pqbd                                                           !/*pq          2*/
#include <lcs/double.h>                                                         /*!pq          3*/
#include <lcs/cmgcom.h>                                                         /*!pq          4*/
      data itt /4,3,3,2,2,1/, delta /2*dp0,3*0.8d0,1.2d0/, emx /2.d2/           !/*pq          5*/
      end                                                                       !/*pq          6*/
