!     $Id: set_i.F,v 1.4 2002/03/27 18:15:23 gwm Exp $                        !/*se          1*/
      subroutine set_i                                                          !/*se          2*/
#include <lcs/double.h>                                                         /*!se          3*/
#include <lcs/bankb.h>                                                          /*!se          4*/
      nabov=0                                                                   !/*se          5*/
      nbelo=0                                                                   !/*se          6*/
      return                                                                    !/*se          7*/
      end                                                                       !/*se          8*/
