!     $Id: bdhc.F,v 1.4 2002/03/27 18:13:49 gwm Exp $                         !/*bd          1*/
      block data bdhc                                                           !/*bd          2*/
#include <htape3x/charhc.h>                                                     /*!bd          3*/
      data msub /'hcnvout','bcdtp','bintp'/                                     !/*bd          4*/
      data isub /ndef*'        '/                                               !/*bda         1*/
      end                                                                       !/*bd          6*/
