# Generated automatically from Makefile.in by configure.
# $Id: Makefile.w32,v 1.1 2002/07/22 17:04:18 jxh Exp $

include Makefile.h

# SOURCEDIR is path relative to this 'make'
SOURCEDIR = ${srcdir}
# INCLUDE directory is one level up from this SOURCEDIR
INCLUDE = -I${SOURCEDIR}/../include

# construct a list of source files for makedepend to use
FSRCS := $(wildcard ${SOURCEDIR}/*.F)
HDRS := $(wildcard ${INCLUDE}/*.h) $(wildcard ${INCLUDE}/*/*.h)
FOBJS := $(notdir $(patsubst %.F,%.o,${FSRCS}))

# DATASRC directory is where ascii files live
DATASRC = ${SOURCEDIR}\..\..\Data\LCS

# Define a few extra symbols for FFLAGS
DEFS += -DHCNV -DMAIN

# Sources in this directory depend upon BLOCK DATA references, 
# BUT there is only one target to make, which is an executable
TARGET = hcnv

BDOBJS = bdhc.o
# Object Files
OBJS = hcnv.o ckchar.o exemes.o expire.o getexm.o inqire.o leng.o \
              nxtsym.o unique.o uopen.o

#----------------------------
# builds and executes a program that translates text to binary
all :  ${TARGET}
	@${ECHO} "$@ completed."

# Help file is the shared one at the top level
help :
	@more ${SOURCEDIR}/../../Readme.make

# You should not install until you 'make all' and 'make tests'
# We only enforce 'make all'
install : all
	@${SOURCEDIR}/../../config/install-sh -c bertin ${datadir}/bertin
	@${ECHO} "Install of bertin into ${datadir} complete."

# - - - - - - - - - - - - - - - - - - - 
# how .o files emerge from .F files
%.o : %.F
	${FCOMP} /compile_only ${FPPFLAGS} ${FFLAGS} ${FDEFS} /object:$@ ${srcdir}\$(<F)

# - - - - - - - - - - - - - - - - - - -

# the target - make executable hcnv program, copy the input file from source dir,
# execute hcnv program, rename the binary output to bertin, remove excess files
${TARGET} : ${BDOBJS} ${OBJS}
	${FCOMP} ${FFLAGS} ${LDFLAGS} /exe:$@ ${BDOBJS} ${OBJS}
	@${CP} ${DATASRC}\bcdtp .
	-@${RM} bintp hcnvout
	.\$@ < ${SOURCEDIR}\$@.input
	@${CP} bintp bertin
	-@${RM} bcdtp bintp hcnvout

# force make to execute every time for PHONY targets
.PHONY : clean distclean 

# Target clean should remove intermediate files and .o files but leave executables alone
clean :
	@-${RM} ${CLEANFILES} bertin hcnv.exe

# Target distclean should clean then remove executables and dependency files
distclean : clean
	@${RM} -f ${TARGET} bertin
	@-${RM} -f ${DISTCLEANFILES}
	@-${RM} -f ${CONFFILES}

depend.mk: ${FSRCS} ${HDRS}
	@${ECHO} "making dependencies for ${SOURCEDIR}"
	@makedepend -f- -- $(FFLAGS) ${INCLUDE} -- $(FSRCS) | \
	sed 's%^${SOURCEDIR}/%%' >depend.mk
	@${ECHO} "depend.mk for ${SOURCEDIR} has been generated"

# include depend.mk

# DO NOT DELETE THIS LINE -- makedepend depends on it.
