[CROSS_SEARCH]
KENKYU_KIKAN_FROM=2023
KENKYU_YOSAN_FROM=500

# SWITCH
[KAKEN_SWITCH]
KENKYU_KIKAN_SYNC=true
EXTRACTION=false
[AMED_SWITCH]
KENKYU_KIKAN_SYNC=true
EXTRACTION=false
[JST_SWITCH]
KENKYU_KIKAN_SYNC=true
EXTRACTION=true

# KAKEN
[KAKEN_SOURCE]
KENKYU_KIKAN_URL=https://www-kaken.jsps.go.jp/kaken1/kikanList.do
[CINII_OPENSEARCH]
URL=https://kaken.nii.ac.jp/opensearch/
APPID=8if8E9qcvGLiwX6YrbW5
USE_CACHE=True
[KAKEN_OPTION]
RESULTS_PER_PAGE=500
[KAKEN_SEARCH]
KENKYU_KIKAN_FILE=settings/extract_kenkyu_kikan/kaken.yaml

# AMED
[AMED_SOURCE]
URL=https://grants.jst.go.jp/search/
[AMED_OPTION]
RESULTS_PER_PAGE=500
[AMED_SEARCH]
KENKYU_KIKAN_FILE=settings/extract_kenkyu_kikan/amed.yaml
KENKYU_KIKAN_CONDITION=1

# JST
[JST_SOURCE]
URL=https://grants.jst.go.jp/search/
[JST_OPTION]
RESULTS_PER_PAGE=500
[JST_SEARCH]
KENKYU_KIKAN_FILE=settings/extract_kenkyu_kikan/jst.yaml
KENKYU_KIKAN_CONDITION=1

# COMMON
[OPTION]
ZENKOKU_KENKYU_KIKAN_SYNC=false
IDENTIFY_PREFECTURE=true
OUTPUT_PLACE_PATH=./output
MAX_WAIT_TIME=0.1
SLEEP_TIME=5
PAGE_RETRY=3
