!     $Id: aabini.F,v 1.4 2002/03/27 18:14:38 gwm Exp $                       !/*aa          1*/
      subroutine aabini (aaname)                                                !/*aa          2*/
!                                                                     *         !/*aa          3*/
      call errorf ('aabini')                                                    !/*aa          4*/
      end                                                                       !/*aa          5*/
