# Generated automatically from Makefile.in by configure.
# $Id: Makefile.w32,v 1.1 2002/07/22 17:04:19 jxh Exp $

include Makefile.h

# SOURCEDIR is path relative to this 'make'
SOURCEDIR = ${srcdir}
# INCLUDE directory  is two  levels up from this SOURCEDIR
INCLUDE = -I${SOURCEDIR}/../../include

# make a list of source files for makedepend to use
CSRCS := $(wildcard ${SOURCEDIR}/*.c)
HDRS := $(wildcard $INCLUDE{}/*.h) $(wildcard ${INCLUDE}/*/*.h)
COBJS := $(notdir $(patsubst %.c,%.o,${CSRCS}))

### NO STATIC TARGETS - NO SHARED OBJECT TARGETS
### dlmod is a stand alone executable  for shared objects

OBJ = dl-mod.o

#----------------------------
all : dl-mod
	@${ECHO} "$@ completed."

# Help file is the shared one at the top level
help :
	@more ${SOURCEDIR}/../../../Readme.make

# - - - - - - - - - - - - - - - - - - - 
# how .o files emerge from .c files
%.o : %.c
	${CCOMP} -c  ${CFLAGS} ${CDEFS}  $< -o $@
# - - - - - - - - - - - - - - - - - - - 

dl-mod :	${OBJ}
	${CCOMP} ${CFLAGS} ${LDFLAGS} ${SOLDFLAGS} -o dl-mod  ${OBJ}  ${SOLIBS}

# force make to execute every time for PHONY targets
.PHONY : clean distclean

# Target clean should remove intermediate files and .o files but leave executables alone
clean :
	@-${RM} ${CLEANFILES}

# Target distclean should clean then remove executables and dependency files
distclean : clean
	@-${RM} -f dl-mod dl-mod.*
	@-${RM} -f ${DISTCLEANFILES}
	@-${RM} -f ${CONFFILES}

depend.mk: ${CSRCS} ${HDRS}
	@${ECHO} "making dependencies for ${SOURCEDIR}"
	@makedepend -f- -- $(CFLAGS) ${INCLUDE} -- $(CSRCS) | \
	sed 's%^${SOURCEDIR}/%%' >depend.mk
	@${ECHO} "depend.mk for ${SOURCEDIR} has been generated"

# include depend.mk

# DO NOT DELETE THIS LINE -- makedepend depends on it.
