# Generated automatically from Makefile.in by configure.
# $Id: Makefile.w32,v 1.1 2002/07/22 17:04:21 jxh Exp $

include Makefile.h

# SOURCEDIR is path relative to this 'make'
SOURCEDIR = ${srcdir}
# INCLUDE directory  is two  levels up from this SOURCEDIR
INCLUDE = -I${SOURCEDIR}/../../include

# construct a list of source files for makedepend to use
FSRCS := $(wildcard ${SOURCEDIR}/*.F)
HDRS := $(wildcard ${INCLUDE}/*.h) $(wildcard ${INCLUDE}/*/*.h)
FOBJS := $(notdir $(patsubst %.F,%.o,${FSRCS}))

# Target meshtal is only a statically built one
TARGET = meshtal

# Object files
OBJS = dfact.o gd1tal.o gd2tal.o gd3tal.o gdtal.o rfact.o tallmg.o trfdat.o

#----------------------------
# make rules for static and shared targets
all : ${TARGET}.${STATSUF}
	@${ECHO} "$@ completed."

# Help file is the shared one at the top level
help :
	@more ${SOURCEDIR}/../../../Readme.make

# - - - - - - - - - - - - - - - - - - - 
# how .o files emerge from .F files
%.o : %.F
	${FCOMP} /compile_only ${FPPFLAGS} ${FFLAGS} ${FDEFS} /object:$@ ${srcdir}\$(<F)
# - - - - - - - - - - - - - - - - - - - 

# the target
${TARGET}.${STATSUF} : ${OBJS}
	${AR_CMD}${TARGET}.${STATSUF} ${OBJS}

# force make to execute every time for PHONY targets
.PHONY : clean distclean 

# Target clean should remove intermediate files and .o files but leave executables alone
clean :
	@-${RM} ${CLEANFILES}

# Target distclean should clean then remove executables and dependency files
distclean : clean
	@${RM} -f ${TARGET}.*
	@-${RM} -f ${DISTCLEANFILES}
	@-${RM} -f ${CONFFILES}

depend.mk: ${FSRCS} ${HDRS}
	@${ECHO} "making dependencies for ${SOURCEDIR}"
	@makedepend -f- -- $(FFLAGS) ${INCLUDE} -- $(FSRCS) | \
	sed 's%^${SOURCEDIR}/%%' >depend.mk
	@${ECHO} "depend.mk for ${SOURCEDIR} has been generated"

# include depend.mk

# DO NOT DELETE THIS LINE -- makedepend depends on it.

