# Generated automatically from Makefile.in by configure.
# $Id: Makefile.w32,v 1.1 2002/07/22 17:04:18 jxh Exp $

include Makefile.h

# SOURCEDIR is path relative to this 'make'
SOURCEDIR = ${srcdir}
# INCLUDE directory is one level up from this SOURCEDIR
# INCLUDE = -I${SOURCEDIR}/../include

# construct a list of source files for makedepend to use
FSRCS := $(wildcard ${SOURCEDIR}/*.F)
HDRS := $(wildcard ${INCLUDE}/*.h) $(wildcard ${INCLUDE}/*/*.h)
FOBJS := $(notdir $(patsubst %.F,%.o,${FSRCS}))

# Add optimization settings to front of FFLAGS
FFLAGS += ${FOPT} 

# Sources in this directory depend upon BLOCK DATA references, 
# BUT there is only one target to make, which is an executable
TARGET = htape3x

BDOBJS = bdht.o bdsr.o blkd.o
# Object files
OBJS = htape3.o accum.o bin.o bininu.o                                          \
pointr.o ipterr.o putm.o status.o                                \
ckchar.o conv.o cov11.o csevl.o edit.o                                          \
edit1.o edit11.o edit13.o edit14.o edit15.o edit16.o edit3.o edit5.o edit6.o    \
edit7.o edit8.o edit8a.o edit8b.o edit9.o eotap.o erf_rep.o erfc_rep.o          \
errorf.o exemes.o expire.o filden.o fixe.o flin.o forec.o getexm.o getjdt.o     \
hed3.o input.o inqire.o insig.o jptx.o krack.o leng.o ltran.o newfil.o nxtsym.o \
opt1.o opt11.o opt13.o opt14.o opt15.o opt16.o opt3.o opt4.o opt5.o opt6.o      \
opt7.o opt8.o opt9.o pcov11.o pcov5.o peek.o recels.o resp.o respin.o secnd.o   \
getidt.o skipper.o sorun.o srchn.o stepup.o tconin.o tconv.o timeit.o  \
tp10.o tsrcin.o unique.o uopen.o weight.o wght4.o winit.o wtin.o wtin4.o xtp11.o

#----------------------------
# TARGET@ result is an executable program
all : ${TARGET}
	@${ECHO} "$@ completed."

# Help file is the shared one at the top level
help :
	@more ${SOURCEDIR}/../../Readme.make

# You should not install until you 'make all' and 'make tests'
# We only enforce 'make all'
install : all
	@${SOURCEDIR}/../../config/install-sh -c htape3x ${bindir}/htape3x
	@${ECHO} "Install of htape3x into ${bindir} complete."

# - - - - - - - - - - - - - - - - - - - 
# how .o files emerge from .F files
%.o : %.F
	${FCOMP} /compile_only ${FPPFLAGS} ${FFLAGS} ${FDEFS} /object:$@ ${srcdir}\$(<F)

# - - - - - - - - - - - - - - - - - - - 
# the target
${TARGET} : ${BDOBJS} ${OBJS}
	${FCOMP} ${FFLAGS} ${LDFLAGS} /exe:$@ ${BDOBJS}  ${OBJS} ${XLIBS}

# force make to execute every time for PHONY targets
.PHONY : clean distclean 

# Target clean should remove intermediate files and .o files but leave executables alone
clean :
	@-${RM} ${CLEANFILES} htape3x.exe

# Target distclean should clean then remove executables and dependency files
distclean : clean
	@${RM} -f ${TARGET}
	@-${RM} -f ${DISTCLEANFILES}
	@-${RM} -f ${CONFFILES}

depend.mk: ${FSRCS} ${HDRS}
	@${ECHO} "making dependencies for ${SOURCEDIR}"
	@makedepend -f- -- $(FFLAGS) ${INCLUDE} -- $(FSRCS) | \
	sed 's%^${SOURCEDIR}/%%' >depend.mk
	@${ECHO} "depend.mk for ${SOURCEDIR} has been generated"

# include depend.mk

# DO NOT DELETE THIS LINE -- makedepend depends on it.

